version: '3.8'
services:
  postgres-order:
    image: postgres:15
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data

  postgres-product:
    image: postgres:15
    environment:
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass
      POSTGRES_DB: product_db
    ports:
      - "5433:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data

volumes:
  order-db-data:
  product-db-data:
